- name: demo on filters
  hosts: local
  connection: local
  vars:
   topics: linux, shell, ansible, terraform
   tags:
     name: ansible
     project: roboshop
     component: catalogue
  tasks:
  - name: greeting
    ansible.builtin.debug:
      msg: "Hi PMPK, {{ GREETING | default ('Good Morning')}}"

  - name: convert string to list
    ansible.builtin.debug:
     msg: "{{ topics | split(',') }}"

  - name: convert map into list
    ansible.builtin.debug:
     msg: "{{ tags | dict2items }}"