- name: Demo on error handling
  hosts: local
  connection: local
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id roboshop
    register: user_output
    ignore_errors: true
  
  - name: print the output
    ansible.builtin.debug:
      msg: "{{ user_output }}"

  - name: Create user
    ansible.builtin.command: useradd roboshop
    while: user_output.rc != 0